# Generated by Django 4.2.6 on 2023-11-04 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DistrictCode',
        ),
    ]
