# Generated by Django 4.2.6 on 2023-11-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('input', '0002_delete_districtcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('행정동코드', models.CharField(blank=True, max_length=10, null=True)),
                ('행정동명', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
