# Generated by Django 4.2.6 on 2023-11-04 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('output', '0007_districtcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DistrictCode',
        ),
    ]
