# Generated by Django 4.2.7 on 2023-11-17 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("output", "0012_feature_alter_bbang_1_cluster_alter_bbang_2_cluster_and_more"),
    ]

    operations = []
